"""Tests for ``PolicyBundle`` — loading and integrity verification.

The bundle abstraction is what the runtime hands to the WASM evaluator.
These tests need a real ``opa`` binary because they build bundles end-to-
end (yaml → rego → wasm) before exercising the loader. The
``needs_opa`` mark skips them in environments without opa.
"""

from __future__ import annotations

import hashlib
import json
import shutil
from pathlib import Path

import pytest

from fortify.security import (
    BundleIntegrityError,
    BundleLoadError,
    BundleSignatureError,
    PolicyBundle,
    WasmPolicy,
    compile_to_rego,
    compile_to_wasm,
    generate_keypair,
    sign_bytes,
)


_OPA_AVAILABLE = shutil.which("opa") is not None
needs_opa = pytest.mark.skipif(
    not _OPA_AVAILABLE,
    reason="opa not on PATH — install via `brew install opa` to run these tests",
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


_DEMO_YAML = """\
version: 1
roles:
  billing:
    tools:
      refund_order:
        mode: allow
        constraints:
          - args.amount <= 500
"""


def _build_bundle(directory: Path, stem: str = "policy") -> Path:
    """Build a real bundle on disk under ``directory`` and return its path."""
    yaml_path = directory / f"{stem}.yaml"
    yaml_path.write_text(_DEMO_YAML, encoding="utf-8")
    source_hash = hashlib.sha256(_DEMO_YAML.encode("utf-8")).hexdigest()

    rego_text = compile_to_rego(
        {
            "version": 1,
            "roles": {
                "billing": {
                    "tools": {
                        "refund_order": {
                            "mode": "allow",
                            "constraints": ["args.amount <= 500"],
                        }
                    }
                }
            },
        },
        source_hash=source_hash,
    )
    wasm = compile_to_wasm(rego_text).wasm

    (directory / f"{stem}.rego").write_text(rego_text, encoding="utf-8")
    (directory / f"{stem}.wasm").write_bytes(wasm)
    manifest = {
        "version": 1,
        "source": f"{stem}.yaml",
        "source_hash": source_hash,
        "rego_hash": hashlib.sha256(rego_text.encode("utf-8")).hexdigest(),
        "wasm_hash": hashlib.sha256(wasm).hexdigest(),
    }
    (directory / f"{stem}.bundle.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return directory


@pytest.fixture
def bundle_dir(tmp_path: Path) -> Path:
    if not _OPA_AVAILABLE:
        pytest.skip("opa not on PATH")
    return _build_bundle(tmp_path)


def _sign_bundle(directory: Path, private_key_raw: bytes, stem: str = "policy") -> None:
    """Write a detached signature over the manifest's exact on-disk bytes."""
    manifest_bytes = (directory / f"{stem}.bundle.json").read_bytes()
    sig = sign_bytes(manifest_bytes, private_key_raw)
    (directory / f"{stem}.bundle.json.sig").write_bytes(sig)


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


@needs_opa
def test_from_disk_loads_all_artifacts(bundle_dir: Path) -> None:
    """All four files populate the dataclass fields correctly."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    assert bundle.source_path.name == "policy.yaml"
    assert bundle.rego_text.startswith("# Generated by fortify policy build")
    assert bundle.wasm_bytes.startswith(b"\x00asm")
    assert bundle.manifest["version"] == 1


def test_from_disk_rejects_non_directory(tmp_path: Path) -> None:
    """Loader refuses a path that isn't a directory at all."""
    target = tmp_path / "nope"
    with pytest.raises(BundleLoadError, match="not a directory"):
        PolicyBundle.from_disk(target)


def test_from_disk_rejects_empty_directory(tmp_path: Path) -> None:
    """Empty dir → missing manifest error, not a silent fall-through."""
    with pytest.raises(BundleLoadError, match="no .*bundle.json"):
        PolicyBundle.from_disk(tmp_path)


@needs_opa
def test_from_disk_rejects_ambiguous_directory(
    bundle_dir: Path, tmp_path: Path
) -> None:
    """Two bundles in one dir → refuse rather than guess."""
    _build_bundle(bundle_dir, stem="other")
    with pytest.raises(BundleLoadError, match="multiple bundle manifests"):
        PolicyBundle.from_disk(bundle_dir)


@needs_opa
def test_from_disk_rejects_partial_bundle(bundle_dir: Path) -> None:
    """Manifest present but rego missing → caller gets a specific error."""
    (bundle_dir / "policy.rego").unlink()
    with pytest.raises(BundleLoadError, match="missing policy.rego"):
        PolicyBundle.from_disk(bundle_dir)


# ---------------------------------------------------------------------------
# Integrity
# ---------------------------------------------------------------------------


@needs_opa
def test_verify_integrity_passes_for_fresh_bundle(bundle_dir: Path) -> None:
    """A bundle built by the CLI verifies cleanly with no tampering."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    bundle.verify_integrity()  # raises on failure


@needs_opa
def test_verify_integrity_catches_tampered_wasm(bundle_dir: Path) -> None:
    """Flip one byte in the wasm file — verify catches the mismatch."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    # Tamper after loading by editing the in-memory bytes
    bundle.wasm_bytes = bundle.wasm_bytes[:-1] + bytes([(bundle.wasm_bytes[-1] ^ 1)])
    with pytest.raises(BundleIntegrityError, match="wasm hash mismatch"):
        bundle.verify_integrity()


@needs_opa
def test_verify_integrity_catches_tampered_rego(bundle_dir: Path) -> None:
    """Edit the rego text after load — verify catches the mismatch."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    bundle.rego_text = bundle.rego_text + "\n# tampered\n"
    with pytest.raises(BundleIntegrityError, match="rego hash mismatch"):
        bundle.verify_integrity()


@needs_opa
def test_verify_integrity_catches_tampered_source(bundle_dir: Path) -> None:
    """Edit the on-disk yaml after build — verify catches it."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    bundle.source_path.write_text("version: 1\nroles: {}\n", encoding="utf-8")
    with pytest.raises(BundleIntegrityError, match="source.yaml hash mismatch"):
        bundle.verify_integrity()


@needs_opa
def test_verify_integrity_refuses_no_wasm_manifest(bundle_dir: Path) -> None:
    """Manifests built with --no-wasm have wasm_hash=null — refuse them
    for enforcement use."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    bundle.manifest["wasm_hash"] = None
    with pytest.raises(BundleIntegrityError, match="--no-wasm"):
        bundle.verify_integrity()


# ---------------------------------------------------------------------------
# Lazy policy instantiation
# ---------------------------------------------------------------------------


@needs_opa
def test_policy_returns_wasmpolicy(bundle_dir: Path) -> None:
    """Calling .policy() yields a usable WasmPolicy."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    p = bundle.policy()
    assert isinstance(p, WasmPolicy)
    d = p.decide(role="billing", tool="refund_order", args={"amount": 200})
    assert d.allow is True


@needs_opa
def test_policy_is_cached(bundle_dir: Path) -> None:
    """Repeated .policy() calls return the same instance — no re-instantiate."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    assert bundle.policy() is bundle.policy()


# ---------------------------------------------------------------------------
# Signatures (authenticity)
# ---------------------------------------------------------------------------


@needs_opa
def test_unsigned_bundle_has_no_signature(bundle_dir: Path) -> None:
    """A bundle built without --sign-key loads with signature=None."""
    bundle = PolicyBundle.from_disk(bundle_dir)
    assert bundle.is_signed is False
    assert bundle.signature is None


@needs_opa
def test_from_disk_loads_detached_signature(bundle_dir: Path) -> None:
    """A *.bundle.json.sig sidecar populates the signature field."""
    private_raw, _ = generate_keypair()
    _sign_bundle(bundle_dir, private_raw)
    bundle = PolicyBundle.from_disk(bundle_dir)
    assert bundle.is_signed is True
    assert len(bundle.signature) == 64


@needs_opa
def test_verify_signature_passes_for_genuine_signature(bundle_dir: Path) -> None:
    """A signature over the real manifest verifies under the matching pubkey."""
    private_raw, public_raw = generate_keypair()
    _sign_bundle(bundle_dir, private_raw)
    bundle = PolicyBundle.from_disk(bundle_dir)
    bundle.verify_signature(public_raw)  # no raise == pass


@needs_opa
def test_verify_signature_rejects_wrong_key(bundle_dir: Path) -> None:
    """A signature from the platform key doesn't verify under a stranger's key."""
    signer_priv, _ = generate_keypair()
    _, other_pub = generate_keypair()
    _sign_bundle(bundle_dir, signer_priv)
    bundle = PolicyBundle.from_disk(bundle_dir)
    with pytest.raises(BundleSignatureError, match="verification failed"):
        bundle.verify_signature(other_pub)


@needs_opa
def test_verify_signature_rejects_tampered_manifest(bundle_dir: Path) -> None:
    """Sign, then edit the manifest on disk — the signature no longer matches.

    This is the attack Phase 5's integrity check couldn't catch: editing
    a file AND updating the manifest hash to match. With signing, the
    altered manifest bytes break the signature.
    """
    private_raw, public_raw = generate_keypair()
    _sign_bundle(bundle_dir, private_raw)
    # Tamper with the manifest after signing.
    manifest_path = bundle_dir / "policy.bundle.json"
    doctored = json.loads(manifest_path.read_text())
    doctored["wasm_hash"] = "0" * 64
    manifest_path.write_text(json.dumps(doctored, indent=2, sort_keys=True) + "\n")

    bundle = PolicyBundle.from_disk(bundle_dir)
    with pytest.raises(BundleSignatureError, match="verification failed"):
        bundle.verify_signature(public_raw)


@needs_opa
def test_verify_signature_raises_when_unsigned(bundle_dir: Path) -> None:
    """Calling verify_signature on an unsigned bundle is a clear error."""
    _, public_raw = generate_keypair()
    bundle = PolicyBundle.from_disk(bundle_dir)
    with pytest.raises(BundleSignatureError, match="no signature"):
        bundle.verify_signature(public_raw)


# ---------------------------------------------------------------------------
# from_parts — in-memory bundles (the shape the platform serves over HTTP)
# ---------------------------------------------------------------------------


def _make_parts(constraints=("args.amount <= 500",)):
    """Compile a tiny policy and return (wasm_bytes, manifest_bytes)."""
    payload = {
        "version": 1,
        "roles": {
            "billing": {
                "tools": {
                    "refund_order": {"mode": "allow", "constraints": list(constraints)}
                }
            }
        },
    }
    rego = compile_to_rego(payload)
    wasm = compile_to_wasm(rego).wasm
    manifest = {
        "version": 1,
        "source": "policy.yaml",
        "source_hash": "0" * 64,
        "rego_hash": hashlib.sha256(rego.encode("utf-8")).hexdigest(),
        "wasm_hash": hashlib.sha256(wasm).hexdigest(),
    }
    manifest_bytes = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    return wasm, manifest_bytes


@needs_opa
def test_from_parts_builds_evaluable_bundle() -> None:
    """An in-memory bundle (no source/rego files) is still evaluable."""
    wasm, manifest_bytes = _make_parts()
    bundle = PolicyBundle.from_parts(wasm_bytes=wasm, manifest_bytes=manifest_bytes)
    assert bundle.source_path is None
    assert bundle.rego_text == ""
    d = bundle.policy().decide(role="billing", tool="refund_order", args={"amount": 200})
    assert d.allow is True


@needs_opa
def test_from_parts_integrity_checks_wasm_hash_only() -> None:
    """Integrity passes (source/rego skipped), and a wasm/hash mismatch fails."""
    wasm, manifest_bytes = _make_parts()
    PolicyBundle.from_parts(
        wasm_bytes=wasm, manifest_bytes=manifest_bytes
    ).verify_integrity()  # no raise — source/rego checks skipped, wasm matches

    tampered = wasm[:-1] + bytes([wasm[-1] ^ 1])
    with pytest.raises(BundleIntegrityError, match="wasm hash mismatch"):
        PolicyBundle.from_parts(
            wasm_bytes=tampered, manifest_bytes=manifest_bytes
        ).verify_integrity()


@needs_opa
def test_from_parts_signature_round_trip() -> None:
    """A signature over the manifest bytes verifies under the matching key."""
    wasm, manifest_bytes = _make_parts()
    priv, pub = generate_keypair()
    sig = sign_bytes(manifest_bytes, priv)
    bundle = PolicyBundle.from_parts(
        wasm_bytes=wasm, manifest_bytes=manifest_bytes, signature=sig
    )
    assert bundle.is_signed
    bundle.verify_signature(pub)  # no raise

    _, stranger = generate_keypair()
    with pytest.raises(BundleSignatureError, match="verification failed"):
        bundle.verify_signature(stranger)


def test_from_parts_rejects_non_json_manifest() -> None:
    with pytest.raises(BundleLoadError, match="not valid JSON"):
        PolicyBundle.from_parts(wasm_bytes=b"\x00asm", manifest_bytes=b"not json{")
