# Generated by hexgate policy build — do not edit by hand.
# Compiled from policy.yaml (sha256: GOLDEN_FIXED_HASH).
# Regenerate with: hexgate policy build <source>

package hexgate.policy

import rego.v1

default allow := false
default requires_approval := false

# Single entrypoint — runtime queries data.hexgate.policy.decision.
decision := {
    "allow": allow,
    "requires_approval": requires_approval,
    "violations": violations,
}

# ---- role: billing -----------------------------------------------------
allow if {
    input.role == "billing"
    input.tool == "fetch"
}

requires_approval if {
    input.role == "billing"
    input.tool == "issue_credit"
    is_number(input.args.amount)
    input.args.amount <= 500
}

violations contains `args.amount <= 500` if {
    input.role == "billing"
    input.tool == "issue_credit"
    not _p_b182706c06
}

allow if {
    input.role == "billing"
    input.tool == "read_file"
}

allow if {
    input.role == "billing"
    input.tool == "refund_order"
    is_number(input.args.amount)
    input.args.amount <= 500
    input.args.currency == "USD"
    input.args.template in ["a", "b"]
    not input.args.priority in ["urgent"]
    input.args.confirmed == true
    is_number(input.args.payment.amount)
    input.args.payment.amount <= 100
    input.ctx.department == "finance"
    is_number(input.ctx.clearance_level)
    input.ctx.clearance_level >= 3
    input.ctx.region in ["EU", "UK"]
}

violations contains `args.amount <= 500` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_b182706c06
}

violations contains `args.currency == "USD"` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_8bcb53951e
}

violations contains `args.template in ["a", "b"]` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_066518c099
}

violations contains `args.priority not in ["urgent"]` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_e5bd576175
}

violations contains `args.confirmed == true` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_ce25e566f4
}

violations contains `args.payment.amount <= 100` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_ee4b81b8b6
}

violations contains `ctx.department == "finance"` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_3420c2e5f0
}

violations contains `ctx.clearance_level >= 3` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_e401e5cd56
}

violations contains `ctx.region in ["EU", "UK"]` if {
    input.role == "billing"
    input.tool == "refund_order"
    not _p_b7b1e13455
}

allow if {
    input.role == "billing"
    input.tool == "agent.run"
}

# ---- role: default -----------------------------------------------------
allow if {
    not input.role in {"billing", "support"}
    input.tool == "web_search"
}

allow if {
    not input.role in {"billing", "support"}
    input.tool == "agent.run"
}

# ---- role: support -----------------------------------------------------
allow if {
    input.role == "support"
    input.tool == "fetch"
}

requires_approval if {
    input.role == "support"
    input.tool == "issue_credit"
    is_number(input.args.amount)
    input.args.amount <= 500
}

violations contains `args.amount <= 500` if {
    input.role == "support"
    input.tool == "issue_credit"
    not _p_b182706c06
}

allow if {
    input.role == "support"
    input.tool == "read_file"
}

allow if {
    input.role == "support"
    input.tool == "agent.run"
}

_p_066518c099 if {
    input.args.template in ["a", "b"]
}

_p_3420c2e5f0 if {
    input.ctx.department == "finance"
}

_p_8bcb53951e if {
    input.args.currency == "USD"
}

_p_b182706c06 if {
    is_number(input.args.amount)
    input.args.amount <= 500
}

_p_b7b1e13455 if {
    input.ctx.region in ["EU", "UK"]
}

_p_ce25e566f4 if {
    input.args.confirmed == true
}

_p_e401e5cd56 if {
    is_number(input.ctx.clearance_level)
    input.ctx.clearance_level >= 3
}

_p_e5bd576175 if {
    not input.args.priority in ["urgent"]
}

_p_ee4b81b8b6 if {
    is_number(input.args.payment.amount)
    input.args.payment.amount <= 100
}

# Sentinel: keeps `violations` defined even when no constraint rules exist.
violations contains "__never__" if false

