"""Security helpers for policies and enforcement."""

from fortify.security.errors import ApprovalRequiredError, PolicyDeniedError
from fortify.security.models import (
    AgentPolicy,
    BaseToolPolicy,
    FileScope,
    FileToolPolicy,
    PolicyMode,
    ToolPolicy,
)
from fortify.security.constraints import (
    Constraint,
    ConstraintParseError,
    check_constraints,
    evaluate_constraint,
    parse_constraint,
)
from fortify.security.binding import (
    PolicyBinding,
    PolicyBindingError,
    ResolvedPolicy,
    resolve_policy,
)
from fortify.security.bundle import (
    BundleIntegrityError,
    BundleLoadError,
    BundleSignatureError,
    PolicyBundle,
    SignedBundle,
    build_signed_bundle,
)
from fortify.security.signing import (
    SignatureError,
    decode_key,
    encode_key,
    generate_keypair,
    public_key_for,
    sign_bytes,
    verify_bytes,
)
from fortify.security.decision import (
    Decision,
    DecisionOutcome,
    PolicyEngine,
    Verdict,
)
from fortify.security.policy import (
    authorize_tool_call,
    authorize_tool_call_wasm,
    default_agent_policy,
    evaluate_tool_call,
    evaluate_tool_call_wasm,
    get_tool_policy,
    load_policy,
    verdict_from_rego,
)
from fortify.security.policy_set import (
    DEFAULT_ROLE_NAME,
    PolicySet,
    PolicySetError,
    load_policy_map,
    load_policy_set,
    load_policy_set_from_dict,
)
from fortify.security.rego import compile_default_only, compile_to_rego
from fortify.security.rego_wasm import (
    DEFAULT_ENTRYPOINTS,
    OpaNotFoundError,
    WasmArtifact,
    WasmCompileError,
    compile_to_wasm,
)
from fortify.security.source import (
    BundleDirPolicySource,
    PlatformPolicySource,
    PolicySource,
    YamlPolicySource,
)
from fortify.security.wasm_engine import (
    DEFAULT_ENTRYPOINT,
    RegoVerdict,
    WasmEvalError,
    WasmPolicy,
)

__all__ = [
    "AgentPolicy",
    "BaseToolPolicy",
    "PolicyBinding",
    "PolicyBindingError",
    "ResolvedPolicy",
    "resolve_policy",
    "Constraint",
    "ConstraintParseError",
    "DEFAULT_ENTRYPOINT",
    "DEFAULT_ENTRYPOINTS",
    "DEFAULT_ROLE_NAME",
    "Decision",
    "FileScope",
    "FileToolPolicy",
    "ApprovalRequiredError",
    "BundleDirPolicySource",
    "BundleIntegrityError",
    "BundleLoadError",
    "BundleSignatureError",
    "OpaNotFoundError",
    "PlatformPolicySource",
    "PolicyBundle",
    "PolicySource",
    "YamlPolicySource",
    "SignatureError",
    "PolicyDeniedError",
    "PolicyMode",
    "PolicySet",
    "RegoVerdict",
    "PolicySetError",
    "SignedBundle",
    "ToolPolicy",
    "WasmArtifact",
    "WasmCompileError",
    "WasmEvalError",
    "WasmPolicy",
    "DecisionOutcome",
    "PolicyEngine",
    "Verdict",
    "authorize_tool_call",
    "authorize_tool_call_wasm",
    "evaluate_tool_call",
    "evaluate_tool_call_wasm",
    "verdict_from_rego",
    "build_signed_bundle",
    "check_constraints",
    "compile_default_only",
    "compile_to_rego",
    "compile_to_wasm",
    "decode_key",
    "encode_key",
    "generate_keypair",
    "public_key_for",
    "sign_bytes",
    "verify_bytes",
    "default_agent_policy",
    "evaluate_constraint",
    "get_tool_policy",
    "load_policy",
    "load_policy_map",
    "load_policy_set",
    "load_policy_set_from_dict",
    "parse_constraint",
]
