"""Compile a Fortify ``policy.yaml`` document into a Rego policy module.

The compiler is a pure-Python transformation: parsed YAML payload →
``PolicySet`` (which flattens ``inherits:`` and drops ``is_mixin:`` entries)
→ a Rego source string suitable for ``opa build -t wasm``.

Why this lives in the SDK (not just the platform): the same compiler runs
in three places — the platform's save-time pipeline, the ``fortify policy
build`` CLI a dev uses for local iteration, and CI/CD wrapper scripts.
Identical artifacts everywhere; the only thing the platform adds is the
Ed25519 signature on the resulting bundle.

Output structure
----------------

For each concrete role's allowed / approval-required tool, the compiler
emits one Rego rule per ``(role, tool)`` pair, guarded by ``input.role``
and ``input.tool``:

    package fortify.policy

    default allow := false
    default requires_approval := false

    # ---- role: billing ----
    allow if {
        input.role == "billing"
        input.tool == "refund_order"
        input.args.amount <= 500
        input.args.currency in ["USD", "EUR"]
    }

    # ---- role: support ----
    requires_approval if {
        input.role == "support"
        input.tool == "issue_credit"
        input.args.amount <= 500
    }

Deny is implicit — a tool with ``mode: deny`` produces no rule, so neither
``allow`` nor ``requires_approval`` fires, and the runtime treats absence
of an allow as deny (fail-closed).

Constraint translation
----------------------

The grammar already mirrors Rego conditions, so translation is one step:
each ``args.<field>`` path becomes ``input.args.<field>``. We re-use
:func:`parse_constraint` for the AST so the path / operator / literal are
already structured — we don't text-substitute.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from fortify.security.constraints import Constraint, parse_constraint
from fortify.security.models import AgentPolicy, BaseToolPolicy
from fortify.security.policy_set import (
    DEFAULT_ROLE_NAME,
    PolicySet,
    PolicySetError,
    load_policy_set_from_dict,
)


# Rego operators are mostly a superset of ours. ``not in`` needs special
# handling because Rego writes it as ``not (x in y)``; we wrap the body.
_INFIX_OPS = {"==", "!=", "<", "<=", ">", ">="}


def compile_to_rego(
    payload: dict[str, Any],
    *,
    package: str = "fortify.policy",
    source_hash: str | None = None,
) -> str:
    """Render a Rego policy module for ``payload``.

    ``payload`` is the parsed YAML document (the same shape
    :func:`load_policy_set_from_dict` accepts — flat single-policy or
    inline-roles). ``source_hash`` is the sha256 of the original YAML
    source; included in the file header so the artifact is traceable
    back to its source. When ``None``, the header is computed from
    ``payload`` itself.
    """
    policy_set = load_policy_set_from_dict(payload)
    if source_hash is None:
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        source_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    lines: list[str] = []
    lines.extend(_header(source_hash, package))
    lines.extend(_default_rules())
    lines.extend(_role_rules(policy_set))
    # Trailing newline — POSIX-friendly + a few editors complain otherwise.
    return "\n".join(lines) + "\n"


def _header(source_hash: str, package: str) -> list[str]:
    return [
        "# Generated by fortify policy build — do not edit by hand.",
        f"# Compiled from policy.yaml (sha256: {source_hash}).",
        "# Regenerate with: fortify policy build <source>",
        "",
        f"package {package}",
        "",
    ]


def _default_rules() -> list[str]:
    return [
        "default allow := false",
        "default requires_approval := false",
        "",
    ]


def _role_rules(policy_set: PolicySet) -> list[str]:
    """Emit one allow/requires_approval rule per (role, tool) decision.

    Roles ordered alphabetically and tools within a role ordered the same
    way so the output is deterministic regardless of dict insertion order
    (Python 3.7+ preserves it, but YAML loaders may differ in edge cases).
    """
    out: list[str] = []
    role_names = sorted(role for role in policy_set.roles)
    for role in role_names:
        policy = policy_set.policy_for(role)
        rules = list(_rules_for_role(role, policy))
        if not rules:
            # Pure deny — skip the section entirely to keep the output tight.
            continue
        out.append(f"# ---- role: {role} {'-' * (60 - len(role))}")
        out.extend(rules)
    return out


def _rules_for_role(role: str, policy: AgentPolicy) -> list[str]:
    """Render rules for one resolved role."""
    out: list[str] = []
    for tool_name in sorted(policy.tools):
        tool_policy = policy.tools[tool_name]
        rendered = _rule_for_tool(role, tool_name, tool_policy)
        if rendered:
            out.extend(rendered)
            out.append("")
    return out


def _rule_for_tool(
    role: str, tool_name: str, tool_policy: BaseToolPolicy
) -> list[str] | None:
    """Render the rule body for a (role, tool) pair, or None for deny."""
    mode = tool_policy.mode
    if mode == "deny":
        return None
    head = "allow" if mode == "allow" else "requires_approval"

    body: list[str] = [
        f'    input.role == "{_escape_string(role)}"',
        f'    input.tool == "{_escape_string(tool_name)}"',
    ]
    for raw_constraint in tool_policy.constraints:
        try:
            constraint = parse_constraint(raw_constraint)
        except Exception as exc:
            # Compile-time validation: refuse to emit Rego for a constraint
            # the SDK can't even parse — keeps platform / CLI artifacts
            # consistent with what the runtime would accept.
            raise PolicySetError(
                f"role {role!r} tool {tool_name!r}: invalid constraint "
                f"{raw_constraint!r}: {exc}"
            ) from exc
        body.append(f"    {_constraint_to_rego(constraint)}")

    return [f"{head} if {{", *body, "}"]


def _constraint_to_rego(constraint: Constraint) -> str:
    """Render one Constraint as a Rego condition line.

    Path translation: ``args.amount`` → ``input.args.amount``. We always
    prefix ``input.`` so the rule body reads from the WASM evaluator's
    input dict (the conventional name in OPA's eval model).
    """
    lhs = "input." + ".".join(constraint.path)
    rhs = _render_literal(constraint.value)
    op = constraint.op
    if op in _INFIX_OPS:
        return f"{lhs} {op} {rhs}"
    if op == "in":
        return f"{lhs} in {rhs}"
    if op == "not in":
        # Rego negates the whole ``in`` expression; semantically identical
        # to "not present in the set."
        return f"not {lhs} in {rhs}"
    # Unreachable given parse_constraint's whitelist, but defensive.
    raise PolicySetError(f"unsupported constraint operator {op!r}")


def _render_literal(value: Any) -> str:
    """Render a literal (string / int / float / bool / list) as Rego source.

    JSON encoding does the right thing for every type we accept: strings
    get double-quoted with escape handling, numbers are bare, booleans
    map to ``true``/``false``, lists are bracketed comma-separated. Rego's
    literal grammar is a superset of JSON for these shapes.
    """
    return json.dumps(value)


def _escape_string(value: str) -> str:
    """Escape a Python string for safe embedding inside Rego ``"..."``.

    Same rules as JSON: backslashes and double-quotes need escaping. We
    use json.dumps + slice to share the implementation.
    """
    return json.dumps(value)[1:-1]


def compile_default_only(policy: AgentPolicy, *, package: str = "fortify.policy") -> str:
    """Compile a flat single-policy ``AgentPolicy`` as a one-role module.

    Convenience for callers that already have an ``AgentPolicy`` model in
    hand (e.g. legacy single-policy agents). Wraps it as the ``default``
    role and delegates to :func:`compile_to_rego`.
    """
    payload = {"version": policy.version, "roles": {DEFAULT_ROLE_NAME: policy.model_dump(exclude_defaults=False)}}
    return compile_to_rego(payload, package=package)
