"""Security helpers for policies and enforcement."""

from hexgate.security.errors import (
    AgentBannedError,
    ApprovalRequiredError,
    PolicyDeniedError,
)
from hexgate.security.bans import (
    EMPTY_BAN_SET,
    BanContentError,
    BanEnforcementEvent,
    BanEntry,
    BanGate,
    BanSet,
    BanSource,
    PlatformBanSource,
    ban_set_from_payload,
    configure_ban_sink,
    get_ban_source,
    resolve_ban_gate,
)
from hexgate.security.models import (
    AGENT_RUN_TOOL,
    AgentPolicy,
    AgentTargetPolicy,
    AgentVia,
    BaseToolPolicy,
    FileScope,
    FileToolPolicy,
    PolicyMode,
    ToolPolicy,
    agent_target_key,
)
from hexgate.security.constraints import (
    Constraint,
    ConstraintParseError,
    check_constraints,
    evaluate_constraint,
    parse_constraint,
)
from hexgate.security.binding import (
    PolicyBinding,
    PolicyBindingError,
    ResolvedPolicy,
    resolve_policy,
)
from hexgate.security.bundle import (
    BundleIntegrityError,
    BundleLoadError,
    BundleSignatureError,
    PolicyBundle,
    SignedBundle,
    build_signed_bundle,
)
from hexgate.security.signing import (
    SignatureError,
    decode_key,
    encode_key,
    generate_keypair,
    public_key_for,
    sign_bytes,
    verify_bytes,
)
from hexgate.security.decision import (
    Decision,
    DecisionOutcome,
    PolicyEngine,
    Verdict,
    combine_role_verdicts,
)
from hexgate.security.policy import (
    authorize_tool_call,
    authorize_tool_call_wasm,
    default_agent_policy,
    evaluate_tool_call,
    evaluate_tool_call_wasm,
    get_tool_policy,
    load_policy,
    verdict_from_rego,
)
from hexgate.security.policy_set import (
    DEFAULT_ROLE_NAME,
    PolicySet,
    PolicySetError,
    load_policy_map,
    load_policy_set,
    load_policy_set_from_dict,
)
from hexgate.security.modules import (
    LayerKind,
    LinkError,
    LinkResult,
    ModuleContent,
    ProjectLinkResult,
    Provenance,
    RuleTrace,
)
from hexgate.security.linker import link, link_policy_set, resolve_for_project
from hexgate.security.analyzer import (
    PolicyLint,
    analyze,
    analyze_project,
    check,
    check_project,
)
from hexgate.security.module_loader import (
    ModuleLoader,
    load_local_modules,
    load_roles,
)
from hexgate.security.rego import compile_default_only, compile_to_rego
from hexgate.security.rego_wasm import (
    DEFAULT_ENTRYPOINTS,
    OpaNotFoundError,
    WasmArtifact,
    WasmCompileError,
    compile_to_wasm,
)
from hexgate.security.source import (
    BundleDirPolicySource,
    PlatformPolicySource,
    PolicyContentError,
    PolicySource,
    YamlPolicySource,
)
from hexgate.security.wasm_engine import (
    DEFAULT_ENTRYPOINT,
    RegoVerdict,
    WasmEvalError,
    WasmPolicy,
)
from hexgate.security.builder import C, PolicyBuilder, RolePolicyBuilder
from hexgate.security.testing import (
    assert_allows,
    assert_denies,
    assert_needs_approval,
)

__all__ = [
    "AGENT_RUN_TOOL",
    "AgentBannedError",
    "AgentPolicy",
    "AgentTargetPolicy",
    "AgentVia",
    "agent_target_key",
    "LayerKind",
    "LinkError",
    "LinkResult",
    "ModuleContent",
    "ModuleLoader",
    "PolicyLint",
    "ProjectLinkResult",
    "Provenance",
    "RuleTrace",
    "analyze",
    "analyze_project",
    "check",
    "check_project",
    "link",
    "link_policy_set",
    "load_local_modules",
    "load_roles",
    "resolve_for_project",
    "EMPTY_BAN_SET",
    "BanContentError",
    "BanEnforcementEvent",
    "BanEntry",
    "BanGate",
    "BanSet",
    "BanSource",
    "PlatformBanSource",
    "ban_set_from_payload",
    "configure_ban_sink",
    "get_ban_source",
    "resolve_ban_gate",
    "C",
    "PolicyBuilder",
    "RolePolicyBuilder",
    "assert_allows",
    "assert_denies",
    "assert_needs_approval",
    "BaseToolPolicy",
    "PolicyBinding",
    "PolicyBindingError",
    "ResolvedPolicy",
    "resolve_policy",
    "Constraint",
    "ConstraintParseError",
    "DEFAULT_ENTRYPOINT",
    "DEFAULT_ENTRYPOINTS",
    "DEFAULT_ROLE_NAME",
    "Decision",
    "FileScope",
    "FileToolPolicy",
    "ApprovalRequiredError",
    "BundleDirPolicySource",
    "BundleIntegrityError",
    "BundleLoadError",
    "BundleSignatureError",
    "OpaNotFoundError",
    "PlatformPolicySource",
    "PolicyBundle",
    "PolicyContentError",
    "PolicySource",
    "YamlPolicySource",
    "SignatureError",
    "PolicyDeniedError",
    "PolicyMode",
    "PolicySet",
    "RegoVerdict",
    "PolicySetError",
    "SignedBundle",
    "ToolPolicy",
    "WasmArtifact",
    "WasmCompileError",
    "WasmEvalError",
    "WasmPolicy",
    "DecisionOutcome",
    "PolicyEngine",
    "Verdict",
    "authorize_tool_call",
    "authorize_tool_call_wasm",
    "combine_role_verdicts",
    "evaluate_tool_call",
    "evaluate_tool_call_wasm",
    "verdict_from_rego",
    "build_signed_bundle",
    "check_constraints",
    "compile_default_only",
    "compile_to_rego",
    "compile_to_wasm",
    "decode_key",
    "encode_key",
    "generate_keypair",
    "public_key_for",
    "sign_bytes",
    "verify_bytes",
    "default_agent_policy",
    "evaluate_constraint",
    "get_tool_policy",
    "load_policy",
    "load_policy_map",
    "load_policy_set",
    "load_policy_set_from_dict",
    "parse_constraint",
]
