"""Compile a Hexgate ``policy.yaml`` document into a Rego policy module.

The compiler is a pure-Python transformation: parsed YAML payload →
``PolicySet`` (which flattens ``inherits:`` and drops ``is_mixin:`` entries)
→ a Rego source string suitable for ``opa build -t wasm``.

Why this lives in the SDK (not just the platform): the same compiler runs
in three places — the platform's save-time pipeline, the ``hexgate policy
build`` CLI a dev uses for local iteration, and CI/CD wrapper scripts.
Identical artifacts everywhere; the only thing the platform adds is the
Ed25519 signature on the resulting bundle.

Output structure
----------------

The module exposes a single ``decision`` entrypoint that returns the
full verdict as a structured object. The runtime evaluates one query
per tool-call and receives back ``{allow, requires_approval, violations}``:

    package hexgate.policy

    import rego.v1

    default allow := false
    default requires_approval := false

    # The single entrypoint the runtime queries.
    decision := {
        "allow": allow,
        "requires_approval": requires_approval,
        "violations": violations,
    }

    # ---- role: billing ----
    allow if {
        input.role == "billing"
        input.tool == "refund_order"
        input.args.amount <= 500
    }

    violations contains `args.amount <= 500` if {
        input.role == "billing"
        input.tool == "refund_order"
        not input.args.amount <= 500
    }

Deny is implicit — a tool with ``mode: deny`` produces no allow rule and
no violation rules, so ``allow`` stays false and the deny reason is
just "no allow rule matched" (caller's job to surface that).

The ``violations`` set carries the raw constraint string from the YAML
verbatim, so deny reasons in production match exactly what the dev
wrote in their policy file.

Constraint translation
----------------------

The grammar already mirrors Rego conditions, so translation is one step:
each ``args.<field>`` path becomes ``input.args.<field>``. We re-use
:func:`parse_constraint` for the AST so the path / operator / literal are
already structured — we don't text-substitute. Every constraint emits
*two* contributions: one positive (added to the allow rule body) and
one negative (a ``violations contains`` rule).
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from hexgate.security.constraints import Constraint, parse_constraint
from hexgate.security.models import AgentPolicy, BaseToolPolicy
from hexgate.security.policy_set import (
    DEFAULT_ROLE_NAME,
    PolicySet,
    PolicySetError,
    load_policy_set_from_dict,
)


# Rego operators are mostly a superset of ours. ``not in`` needs special
# handling because Rego writes it as ``not (x in y)``; we wrap the body.
_INFIX_OPS = {"==", "!=", "<", "<=", ">", ">="}


def compile_to_rego(
    payload: dict[str, Any],
    *,
    package: str = "hexgate.policy",
    source_hash: str | None = None,
) -> str:
    """Render a Rego policy module for ``payload``.

    ``payload`` is the parsed YAML document (the same shape
    :func:`load_policy_set_from_dict` accepts — flat single-policy or
    inline-roles). ``source_hash`` is the sha256 of the original YAML
    source; included in the file header so the artifact is traceable
    back to its source. When ``None``, the header is computed from
    ``payload`` itself.
    """
    policy_set = load_policy_set_from_dict(payload)
    if source_hash is None:
        canonical = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        source_hash = hashlib.sha256(canonical.encode("utf-8")).hexdigest()

    lines: list[str] = []
    lines.extend(_header(source_hash, package))
    lines.extend(_decision_scaffold())
    lines.extend(_role_rules(policy_set))
    lines.extend(_violations_sentinel())
    # Trailing newline — POSIX-friendly + a few editors complain otherwise.
    return "\n".join(lines) + "\n"


def _header(source_hash: str, package: str) -> list[str]:
    return [
        "# Generated by hexgate policy build — do not edit by hand.",
        f"# Compiled from policy.yaml (sha256: {source_hash}).",
        "# Regenerate with: hexgate policy build <source>",
        "",
        f"package {package}",
        "",
        "import rego.v1",
        "",
    ]


def _decision_scaffold() -> list[str]:
    """The top-level decision object + default boolean rules.

    Every rendered module has exactly this scaffold; the per-role rules
    contribute to ``allow``, ``requires_approval``, and ``violations``
    via the rules emitted below.
    """
    return [
        "default allow := false",
        "default requires_approval := false",
        "",
        "# Single entrypoint — runtime queries data.hexgate.policy.decision.",
        "decision := {",
        '    "allow": allow,',
        '    "requires_approval": requires_approval,',
        '    "violations": violations,',
        "}",
        "",
    ]


def _violations_sentinel() -> list[str]:
    """Keep ``violations`` defined even for constraint-free policies.

    Without at least one ``violations contains`` rule in the module,
    opa flags the symbol as unsafe and refuses to build. The sentinel
    body is ``false`` so it never contributes — the set stays empty
    in the happy path.
    """
    return [
        "# Sentinel: keeps `violations` defined even when no constraint rules exist.",
        'violations contains "__never__" if false',
        "",
    ]


def _role_rules(policy_set: PolicySet) -> list[str]:
    """Emit per-role allow / requires_approval / violations rules.

    Roles ordered alphabetically and tools within a role ordered the same
    way so the output is deterministic regardless of dict insertion order
    (Python 3.7+ preserves it, but YAML loaders may differ in edge cases).
    """
    out: list[str] = []
    role_names = sorted(role for role in policy_set.roles)
    for role in role_names:
        policy = policy_set.policy_for(role)
        rules = list(_rules_for_role(role, policy))
        if not rules:
            # Pure deny — skip the section entirely to keep the output tight.
            continue
        out.append(f"# ---- role: {role} {'-' * (60 - len(role))}")
        out.extend(rules)
    return out


def _rules_for_role(role: str, policy: AgentPolicy) -> list[str]:
    """Render rules for one resolved role (allow + violations per tool)."""
    out: list[str] = []
    for tool_name in sorted(policy.tools):
        tool_policy = policy.tools[tool_name]
        rendered = _rules_for_tool(role, tool_name, tool_policy)
        if rendered:
            out.extend(rendered)
    return out


def _rules_for_tool(
    role: str, tool_name: str, tool_policy: BaseToolPolicy
) -> list[str]:
    """Render the rule(s) for a (role, tool) pair.

    For ``deny`` mode: emit nothing (absence of a rule IS the deny).
    For ``allow`` / ``approval_required``: emit the positive rule plus
    one ``violations contains`` rule per constraint (the negation).
    """
    mode = tool_policy.mode
    if mode == "deny":
        return []
    head = "allow" if mode == "allow" else "requires_approval"

    # Parse all constraints up-front — surfaces bad grammar at compile time.
    parsed: list[tuple[str, Constraint]] = []
    for raw_constraint in tool_policy.constraints:
        try:
            parsed.append((raw_constraint, parse_constraint(raw_constraint)))
        except Exception as exc:
            raise PolicySetError(
                f"role {role!r} tool {tool_name!r}: invalid constraint "
                f"{raw_constraint!r}: {exc}"
            ) from exc

    out: list[str] = []
    out.extend(_positive_rule(role, tool_name, head, parsed))
    out.append("")
    for raw, constraint in parsed:
        out.extend(_violation_rule(role, tool_name, raw, constraint))
        out.append("")
    return out


def _positive_rule(
    role: str,
    tool_name: str,
    head: str,
    parsed: list[tuple[str, Constraint]],
) -> list[str]:
    """``allow if { role; tool; constraint1; constraint2; ... }``."""
    body = [
        f'    input.role == "{_escape_string(role)}"',
        f'    input.tool == "{_escape_string(tool_name)}"',
    ]
    for _, constraint in parsed:
        body.append(f"    {_constraint_to_rego(constraint)}")
    return [f"{head} if {{", *body, "}"]


def _violation_rule(
    role: str,
    tool_name: str,
    raw_constraint: str,
    constraint: Constraint,
) -> list[str]:
    """``violations contains <raw> if { role; tool; not constraint }``.

    The membership value is the original constraint string from the YAML
    so deny reasons match exactly what the dev wrote.
    """
    return [
        f"violations contains {_rego_string(raw_constraint)} if {{",
        f'    input.role == "{_escape_string(role)}"',
        f'    input.tool == "{_escape_string(tool_name)}"',
        f"    not {_constraint_to_rego(constraint)}",
        "}",
    ]


def _constraint_to_rego(constraint: Constraint) -> str:
    """Render one Constraint as a Rego condition line.

    Path translation: ``args.amount`` → ``input.args.amount``. We always
    prefix ``input.`` so the rule body reads from the WASM evaluator's
    input dict (the conventional name in OPA's eval model).
    """
    lhs = "input." + ".".join(constraint.path)
    rhs = _render_literal(constraint.value)
    op = constraint.op
    if op in _INFIX_OPS:
        return f"{lhs} {op} {rhs}"
    if op == "in":
        return f"{lhs} in {rhs}"
    if op == "not in":
        # Rego negates the whole ``in`` expression; semantically identical
        # to "not present in the set."
        return f"not {lhs} in {rhs}"
    # Unreachable given parse_constraint's whitelist, but defensive.
    raise PolicySetError(f"unsupported constraint operator {op!r}")


def _render_literal(value: Any) -> str:
    """Render a literal (string / int / float / bool / list) as Rego source.

    JSON encoding does the right thing for every type we accept: strings
    get double-quoted with escape handling, numbers are bare, booleans
    map to ``true``/``false``, lists are bracketed comma-separated. Rego's
    literal grammar is a superset of JSON for these shapes.
    """
    return json.dumps(value)


def _escape_string(value: str) -> str:
    """Escape a Python string for safe embedding inside Rego ``"..."``.

    Same rules as JSON: backslashes and double-quotes need escaping. We
    use json.dumps + slice to share the implementation.
    """
    return json.dumps(value)[1:-1]


def _rego_string(value: str) -> str:
    """Render a string as a Rego literal — backticks when safe, else JSON.

    Backticks are Rego's raw-string syntax: no escape processing inside.
    That's perfect for constraint strings like ``args.currency in ["USD"]``
    where double-quote escaping would be noisy. The fallback to JSON
    handles the rare case where the constraint itself contains a backtick.
    """
    if "`" not in value:
        return f"`{value}`"
    return json.dumps(value)


def compile_default_only(
    policy: AgentPolicy, *, package: str = "hexgate.policy"
) -> str:
    """Compile a flat single-policy ``AgentPolicy`` as a one-role module.

    Convenience for callers that already have an ``AgentPolicy`` model in
    hand (e.g. legacy single-policy agents). Wraps it as the ``default``
    role and delegates to :func:`compile_to_rego`.
    """
    payload = {
        "version": policy.version,
        "roles": {DEFAULT_ROLE_NAME: policy.model_dump(exclude_defaults=False)},
    }
    return compile_to_rego(payload, package=package)
